Jw docs
NOAA-EMC/NCEPLIBS-bufr pull request #302
Opened 2023-01-24 20:02 UTC by jack-woollen

modified:   upds3.f
        modified:   upftbv.f
        modified:   ups.f
        modified:   uptdd.f

2023-01-24 21:05 UTC, edwardhartnett commented
Please use a more descriptive PR title, and also mention the issue in the description. In this case, since you are working on an issue, but not finishing it (i.e. closing it), you can say "Part of #246" in your description.

No need to list the files modified in the description, since they already appear in the review. Instead, describe the purpose of the PR.

Following these guidelines leaves a clear record of our work and provides hyper-linked documentation for our releases.

See the other PRs for examples.

2023-01-24 21:05 UTC, edwardhartnett requested changes

2023-01-24 21:05 UTC, edwardhartnett commented on src/uptdd.f
> +C> @brief this subroutine returns the fxy value of an element in a sequence
Capitalize and punctuation

2023-01-24 21:05 UTC, edwardhartnett commented on src/uptdd.f
> +C> @author woollen @date 1994-01-06
Capitalize your name.

2023-01-24 21:05 UTC, edwardhartnett commented on src/ups.f
> +C> $brief unpacks a real*8 user value from a packed bufr integer
Capitalize and punctuate.

2023-01-24 21:05 UTC, edwardhartnett commented on src/ups.f
> +C> this function unpacks a real*8 user value from a packed
Capitalize and punctuate.

2023-01-24 21:05 UTC, edwardhartnett commented on src/uptdd.f
> +C> @brief this subroutine returns the fxy value of an element in a sequence
Capitalize and punctuate.

2023-01-24 21:52 UTC, jack-woollen commented on src/uptdd.f
> +C> @brief this subroutine returns the fxy value of an element in a sequence
Got it.

2023-01-26 07:44 UTC, edwardhartnett commented on src/upftbv.f
> +C> @author J. Ator @date 2005-11-29
Author at bottom.

2023-01-26 07:45 UTC, edwardhartnett commented on src/usrtpl.f
> +C> @author woollen @date 1994-01-06
Capitalize name.

2023-01-26 07:46 UTC, edwardhartnett commented on src/wrdxtb.f
> +C> @param[in] lundx - integer: Fortran logical unit number associated with DX BUFR table information to be written out
I usually don't let the lines get this long.

2023-01-26 09:33 UTC, jack-woollen commented
@edwardhartnett @jbathegit Another question: does the capitalize and punctuate also apply to the program log and in/out parameter text?

2023-01-26 11:03 UTC, edwardhartnett commented
No for history logs since we are removing them.

Yes for parameters.

2023-01-29 04:01 UTC, edwardhartnett commented on src/moda_ivttmp.F
> +C>  TTMP - space used to store TAG elementS for new sections of a growing subset buffer
The module variable need to be documented with the variables, not up here.

2023-01-29 04:02 UTC, edwardhartnett commented on src/moda_ivttmp.F
> -C>  ??? description of VTMP
This is where the module vars must be documented. Each one gets it's own doxygen block.

2023-01-29 04:05 UTC, edwardhartnett commented on src/uptdd.f
> +C> ient=0 - iret = a count of the total number of child mnemonics within tabd(id,lun)
Probably you want these two items to be bullet points. Try this:

```
C> @remark The interpretation of the return value iret depends upon the input value ient, as follows:
C> - ient=0 - iret = a count of the total number of child mnemonics within tabd(id,lun)
C> - ient>0 - iret = the bit-wise representation of the fxy value corresponding to the ient'th child mnemonic of tabd(id,lun)

```

Note the hyphens.

2023-01-30 22:25 UTC, jbathegit approved these changes

2023-01-30 22:27 UTC, jbathegit commented
@edwardhartnett I'm ready to merge this, but merging is blocked because it says you still have some requested changes that need to be addressed.  Everything's been resolved now (I think), but if you still have some concerns could you please clarify, or else please remove the block on this merge?

2023-01-31 04:55 UTC, edwardhartnett approved these changes

2023-01-31 10:13 UTC, merged